#!bin/bash
unset folder
unset MenuAprovi
unset MenuDocker
unset MenuRanche
unset username
unset token
unset repo
unset NameHost
unset repo
unset NameDir
unset Port
unset Range
unset pathUser
unset pattern
unset pathVol
unset application
unset compose
unset fileCompose
unset fileCompose
unset folderSource
unset app
unset containerid
unset composeTarget
unset approve
unset composeTarget
uset comment
uset answer