version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: artifactory
    networks:
      default:
        ipv4_address: 172.15.0.6
    ports:
     - 8081:8081
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    extra_hosts:
      - "jira.giovanemere.minikube.io:172.15.0.2"
      - "bitbucket.giovanemere.minikube.io:172.15.0.3"
      - "jenkins.giovanemere.minikube.io:172.57.0.4"
      - "postgress.giovanemere.minikube.io:172.57.0.5"
      - "artifactory.giovanemere.minikube.io:127.0.0.1"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    privileged: true

networks:
  default:
    external:
      name: jenkins_docker_db