apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: moodle
spec:
  ports:
    - name: "mysql"
      port: 3306
      targetPort: 3306
  selector:
    app: db
status:
  loadBalancer: {}
