kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-pv-volume1
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: moodle-pv-claim1
    namespace: moodle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/devops/PersistentVolumes/moodle/bitnami/moodledata
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sadbogca855


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pv-claim1
  namespace: moodle
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
