apiVersion: v1
kind: Service
metadata:
  labels:
    app: moodle
  name: moodle
  namespace: moodle
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      nodePort: 32080
    - name: "https"
      port: 443
      targetPort: 8443
  selector:
    app: moodle
