version: '3.4'
services:
  jira:
    image: atlassian/jira-software:latest
    restart: always
    ports:
      - 8082:8080
    volumes:
      - jira-data:/var/atlassian/jira

  bitbucket:
    image: atlassian/bitbucket-server:5.10.1
    restart: always
    ports:
      - 7990:7990
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
volumes:
  jira-data:
  bitbucket-data: