version: '3'

services:
  rancher:
    image: rancher/rancher:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '8443:443'
      - '8080:80'
    volumes:
      - rancher-vol:/var/lib/rancher

volumes:
  rancher-vol: